# Generated by Django 4.1.3 on 2022-11-08 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[('fantastic', 5), ('wonderful', 4), ('Good', 3), ('Ok', 2), ('Bad', 1)], default=5),
        ),
    ]
