# Generated by Django 4.1.3 on 2022-11-09 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='composer',
            field=models.CharField(default='-', max_length=50),
        ),
    ]
