# Generated by Django 4.1.3 on 2022-11-09 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_song_composer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='song',
            name='composer',
            field=models.CharField(default='', max_length=50),
        ),
    ]
