# Generated by Django 4.1.3 on 2022-11-12 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_playlist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='category',
            field=models.CharField(choices=[('pv', 'private'), ('pb', 'public')], default='pv', max_length=2),
        ),
    ]
